name: Build and Bundle


on:  
  push: 
    branches:
      - main
  workflow_dispatch: 

jobs:
  # Wait for up to a minute for previous run to complete, abort if not done by then
  pre-build:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bundle: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run bundle
              
      - name: Deploy bundle to S3 bucket
        uses: swimlane/s3-upload-file-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ env.AWS_BUCKET }}
          file_path: './custom-authorizer.zip'
          file_mime_type: 'application/zip'
