name: Build and Bundle


on:  
  push: 
    branches:
      - main
  workflow_dispatch: 

env:
  S3_BUCKET: 'operfinance-deploys'

jobs:
  # Wait for up to a minute for previous run to complete, abort if not done by then
  pre-build:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bundle: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run bundle
          output-qr-url: 'true' 

      - name: Show URL
        run: echo '${{ env.S3_BUCKET }}' 
              
      - name: Deploy bundle to S3 bucket
        uses: hkusu/s3-upload-action@v2
        id: upload # specify some ID for use in subsequent steps
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: ${{ env.S3_BUCKET }}
          file-path: './custom-authorizer.zip'
          output-qr-url: 'true' 

      - name: Show URL
        run: echo '${{ steps.upload.outputs.qr-url }}' # use this output
